version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "10MB"

  api1: &api
    build: .                # ✅ Vai buildar a imagem local usando seu Dockerfile
    hostname: api1
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=2
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
      # db:
      #   condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.08"
          memory: "40MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true   # ✅ Continua conectando na rede externa dos processors
